name: nf-core-mhcquant-1.2.3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-rmarkdown=1.10
  - openms=2.4.0
  - comet-ms=2016013
  - python=2.7.15
  - mhcflurry=1.2.2
  - fred2=2.0.3
